<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ComposeWindowIcons</RootNamespace>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

</Project>
